/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author wilian_g_cardoso
 */
public class ConversorB extends javax.swing.JFrame {

    /**
     * Creates new form ConversorB
     */
    public ConversorB() {
        initComponents();
        
       //ADD os radion de Origem em grupo
        bgOrigem.add(jRbBinario);
        bgOrigem.add(jRbDecimal);
        bgOrigem.add(jRbOctal);
        bgOrigem.add(jRbHexa);
       //ADD os radion de Destino em grupo
        bgResultado.add(jRbHexaD);
        bgResultado.add(jRbOctalD);
        bgResultado.add(jRbDecimalD);
        bgResultado.add(jRbBinarioD);
        
        jTaOrigem.setText("1");//Deixa definido um valor
        jTaDestino.setText("0");//Deixa definido um valor
        jRbDecimal.setSelected(true);//Deixa definido um radion
        jRbDecimalD.setSelected(true);//Deixa definido um radion
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        bgOrigem = new javax.swing.ButtonGroup();
        bgResultado = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jBtVoltar = new javax.swing.JButton();
        jRbDecimal = new javax.swing.JRadioButton();
        jRbBinario = new javax.swing.JRadioButton();
        jRbOctal = new javax.swing.JRadioButton();
        jRbHexa = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTaOrigem = new javax.swing.JTextArea();
        jRbDecimalD = new javax.swing.JRadioButton();
        jRbBinarioD = new javax.swing.JRadioButton();
        jRbOctalD = new javax.swing.JRadioButton();
        jRbHexaD = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTaDestino = new javax.swing.JTextArea();

        jRadioButton6.setText("jRadioButton2");

        jRadioButton8.setText("jRadioButton4");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jRadioButton7.setText("jRadioButton3");

        jRadioButton5.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtVoltar.setText("Voltar");
        jBtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtVoltarActionPerformed(evt);
            }
        });

        jRbDecimal.setText("Decimal");

        jRbBinario.setText("Binário");

        jRbOctal.setText("Octal");

        jRbHexa.setText("Hexa");

        jTaOrigem.setColumns(20);
        jTaOrigem.setRows(5);
        jTaOrigem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTaOrigemKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTaOrigem);

        jRbDecimalD.setText("Decimal");

        jRbBinarioD.setText("Binário");

        jRbOctalD.setText("Octal");

        jRbHexaD.setText("Hexa");

        jTaDestino.setEditable(false);
        jTaDestino.setColumns(20);
        jTaDestino.setRows(5);
        jScrollPane3.setViewportView(jTaDestino);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtVoltar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRbDecimalD)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRbBinarioD)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRbOctalD)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRbHexaD))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRbDecimal)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRbBinario)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRbOctal)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRbHexa)))
                                .addGap(0, 82, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jBtVoltar)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRbDecimal)
                    .addComponent(jRbBinario)
                    .addComponent(jRbOctal)
                    .addComponent(jRbHexa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRbDecimalD)
                    .addComponent(jRbBinarioD)
                    .addComponent(jRbOctalD)
                    .addComponent(jRbHexaD))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtVoltarActionPerformed
        // TODO add your handling code here:
        dispose();//fecha a tela ao abrir outra
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
    }//GEN-LAST:event_jBtVoltarActionPerformed
//    public void origemKeyRealesed(){
//      //  if(bgOrigem.isSelected(jRbBinario)){
//            
//        }
//    }
    ActionListener listener = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
           // updateOutput();
        }
        
        
    };
    private void jTaOrigemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTaOrigemKeyReleased
        // TODO add your handling code here:
       String numeroConvertido = Integer.toBinaryString(Integer.parseInt(jTaOrigem.getText(), 2)); //CONVERSOR EXEMPLO        
       // numeroConvertido = Integer.toHexString(Integer.parseInt(jTaOrigem.getText(), 16));
      //numeroConvertido = Integer.toOctalString(Integer.parseInt(jTaOrigem.getText(), 8));
        
      jTaDestino.setText(numeroConvertido);
    }//GEN-LAST:event_jTaOrigemKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgOrigem;
    private javax.swing.ButtonGroup bgResultado;
    private javax.swing.JButton jBtVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRbBinario;
    private javax.swing.JRadioButton jRbBinarioD;
    private javax.swing.JRadioButton jRbDecimal;
    private javax.swing.JRadioButton jRbDecimalD;
    private javax.swing.JRadioButton jRbHexa;
    private javax.swing.JRadioButton jRbHexaD;
    private javax.swing.JRadioButton jRbOctal;
    private javax.swing.JRadioButton jRbOctalD;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTaDestino;
    private javax.swing.JTextArea jTaOrigem;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
