/*

 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license

 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template

 */
package Telas;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 *
 *
 * @author wilian_g_cardoso
 *
 */
public class TelaPrincipal extends javax.swing.JFrame {

    //declarando as variaveis
    String memoria;

    double num2, num1;

    char op;

    /**
     *
     * Creates new form TelaPrincipal
     *
     */
    public TelaPrincipal() {

        initComponents();

    }

    /**
     *
     * This method is called from within the constructor to initialize the form.
     *
     * WARNING: Do NOT modify this code. The content of this method is always
     *
     * regenerated by the Form Editor.
     *
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfVisor = new javax.swing.JTextField();
        jBtCE = new javax.swing.JButton();
        jBtApagar = new javax.swing.JButton();
        jBtMemRec = new javax.swing.JButton();
        jBtPorcentagem = new javax.swing.JButton();
        jBtCinco = new javax.swing.JButton();
        jBtDois = new javax.swing.JButton();
        jBtMultplicacao = new javax.swing.JButton();
        jBtIgual = new javax.swing.JButton();
        jBtNove = new javax.swing.JButton();
        jBtSeis = new javax.swing.JButton();
        jBtTres = new javax.swing.JButton();
        jBtOito = new javax.swing.JButton();
        jBtUm = new javax.swing.JButton();
        jBtQuatro = new javax.swing.JButton();
        jBtSete = new javax.swing.JButton();
        jBtDivisao = new javax.swing.JButton();
        jBtZero = new javax.swing.JButton();
        jBtAdicao = new javax.swing.JButton();
        jBtMemoria = new javax.swing.JButton();
        jBtSubtracao = new javax.swing.JButton();
        jBtPonto = new javax.swing.JButton();
        jmbPrincipal = new javax.swing.JMenuBar();
        jmbConversor = new javax.swing.JMenu();
        jmbConversorDeVelocidade = new javax.swing.JMenuItem();
        jmbSair = new javax.swing.JMenu();
        jmbExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtfVisor.setEditable(false);
        jtfVisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfVisorActionPerformed(evt);
            }
        });

        jBtCE.setText("CE");
        jBtCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCEActionPerformed(evt);
            }
        });

        jBtApagar.setText("<-");
        jBtApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtApagarActionPerformed(evt);
            }
        });

        jBtMemRec.setText("M+");
        jBtMemRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtMemRecActionPerformed(evt);
            }
        });

        jBtPorcentagem.setText("%");
        jBtPorcentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPorcentagemActionPerformed(evt);
            }
        });

        jBtCinco.setText("5");
        jBtCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCincoActionPerformed(evt);
            }
        });

        jBtDois.setText("2");
        jBtDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtDoisActionPerformed(evt);
            }
        });

        jBtMultplicacao.setText("X");
        jBtMultplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtMultplicacaoActionPerformed(evt);
            }
        });

        jBtIgual.setText("=");
        jBtIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtIgualActionPerformed(evt);
            }
        });

        jBtNove.setText("9");
        jBtNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtNoveActionPerformed(evt);
            }
        });

        jBtSeis.setText("6");
        jBtSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSeisActionPerformed(evt);
            }
        });

        jBtTres.setText("3");
        jBtTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtTresActionPerformed(evt);
            }
        });

        jBtOito.setText("8");
        jBtOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtOitoActionPerformed(evt);
            }
        });

        jBtUm.setText("1");
        jBtUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtUmActionPerformed(evt);
            }
        });

        jBtQuatro.setText("4");
        jBtQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtQuatroActionPerformed(evt);
            }
        });

        jBtSete.setText("7");
        jBtSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSeteActionPerformed(evt);
            }
        });

        jBtDivisao.setText("/");
        jBtDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtDivisaoActionPerformed(evt);
            }
        });

        jBtZero.setText("0");
        jBtZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtZeroActionPerformed(evt);
            }
        });

        jBtAdicao.setText("+");
        jBtAdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAdicaoActionPerformed(evt);
            }
        });

        jBtMemoria.setText("Memória");
        jBtMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtMemoriaActionPerformed(evt);
            }
        });

        jBtSubtracao.setText("-");
        jBtSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSubtracaoActionPerformed(evt);
            }
        });

        jBtPonto.setText(".");
        jBtPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPontoActionPerformed(evt);
            }
        });

        jmbConversor.setText("Conversor");

        jmbConversorDeVelocidade.setText("Base Numérica");
        jmbConversorDeVelocidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbConversorDeVelocidadeActionPerformed(evt);
            }
        });
        jmbConversor.add(jmbConversorDeVelocidade);

        jmbPrincipal.add(jmbConversor);

        jmbSair.setText("Sair");

        jmbExit.setText("Sair");
        jmbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbExitActionPerformed(evt);
            }
        });
        jmbSair.add(jmbExit);

        jmbPrincipal.add(jmbSair);

        setJMenuBar(jmbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBtCE, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtTres, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtNove, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtMemRec)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jBtDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtDois, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBtUm, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jBtOito, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBtCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jBtQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBtSete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBtZero, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtMultplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtAdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jBtMemoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfVisor)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jBtPorcentagem, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                    .addComponent(jBtMemRec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtCE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtNove, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtOito, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtSete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jBtSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jBtTres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtMultplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBtZero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtAdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBtCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBtDois, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtUm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtMemoria)
                    .addComponent(jBtIgual))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jmbConversorDeVelocidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbConversorDeVelocidadeActionPerformed

        // TODO add your handling code here:
        dispose();

        ConversorB tela = new ConversorB();

        tela.setVisible(true);

    }//GEN-LAST:event_jmbConversorDeVelocidadeActionPerformed


    private void jtfVisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfVisorActionPerformed

        // TODO add your handling code here:

    }//GEN-LAST:event_jtfVisorActionPerformed


    private void jBtApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtApagarActionPerformed

        // TODO add your handling code here:
        //Verifica se há algum valor no visor e apaga o ultimop caractere
        if (jtfVisor.getText().length() > 0) {

            jtfVisor.setText(jtfVisor.getText().substring(0, jtfVisor.getText().length() - 1));

        }

    }//GEN-LAST:event_jBtApagarActionPerformed


    private void jBtTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtTresActionPerformed

        // TODO add your handling code here:
        jtfVisor.setText(jtfVisor.getText() + "3");

    }//GEN-LAST:event_jBtTresActionPerformed

    private void jBtCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCEActionPerformed

        // TODO add your handling code here:
        jtfVisor.setText("");//limpa o visor

    }//GEN-LAST:event_jBtCEActionPerformed

    private void jBtNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtNoveActionPerformed

        // TODO add your handling code here:
        jtfVisor.setText(jtfVisor.getText() + "9");

    }//GEN-LAST:event_jBtNoveActionPerformed

    private void jBtSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSeisActionPerformed

        // TODO add your handling code here:
        jtfVisor.setText(jtfVisor.getText() + "6");

    }//GEN-LAST:event_jBtSeisActionPerformed

    private void jBtOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtOitoActionPerformed

        // TODO add your handling code here:
        jtfVisor.setText(jtfVisor.getText() + "8");

    }//GEN-LAST:event_jBtOitoActionPerformed

    private void jBtCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCincoActionPerformed

        // TODO add your handling code here:
        jtfVisor.setText(jtfVisor.getText() + "5");

    }//GEN-LAST:event_jBtCincoActionPerformed

    private void jBtDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtDoisActionPerformed

        // TODO add your han/dling code here:
        jtfVisor.setText(jtfVisor.getText() + "2");

    }//GEN-LAST:event_jBtDoisActionPerformed

    private void jBtSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSeteActionPerformed

        // TODO add your handling code here:
        jtfVisor.setText(jtfVisor.getText() + "7");

    }//GEN-LAST:event_jBtSeteActionPerformed

    private void jBtQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtQuatroActionPerformed

        // TODO add your handling code here:
        jtfVisor.setText(jtfVisor.getText() + "4");

    }//GEN-LAST:event_jBtQuatroActionPerformed

    private void jBtUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtUmActionPerformed

        // TODO add your handling code here:
        jtfVisor.setText(jtfVisor.getText() + "1");

    }//GEN-LAST:event_jBtUmActionPerformed


    private void jBtMultplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtMultplicacaoActionPerformed

        // TODO add your handling code here:
        num1 = Double.parseDouble(jtfVisor.getText());

        op = '*';

        jtfVisor.setText("");

    }//GEN-LAST:event_jBtMultplicacaoActionPerformed


    private void jBtDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtDivisaoActionPerformed

        // TODO add your handling code here:
        num1 = Double.parseDouble(jtfVisor.getText());

        op = '/';

        jtfVisor.setText("");

    }//GEN-LAST:event_jBtDivisaoActionPerformed


    private void jBtAdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAdicaoActionPerformed

        // TODO add your handling code here:
        num1 = Double.parseDouble(jtfVisor.getText());

        op = '+';

        jtfVisor.setText("");

    }//GEN-LAST:event_jBtAdicaoActionPerformed


    private void jBtZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtZeroActionPerformed

        // TODO add your handling code here:
        jtfVisor.setText(jtfVisor.getText() + "0");

    }//GEN-LAST:event_jBtZeroActionPerformed


    private void jBtSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSubtracaoActionPerformed

        // TODO add your handling code here:
        num1 = Double.parseDouble(jtfVisor.getText());

        op = '-';

        jtfVisor.setText("");

    }//GEN-LAST:event_jBtSubtracaoActionPerformed


    private void jBtMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtMemoriaActionPerformed
        // TODO add your handling code here:

        // Obtém o valor do visor
        String conta = jtfVisor.getText();

        // Verifica se há algum valor no visor
        if (!conta.isEmpty()) {
            // Nome do arquivo onde as contas serão salvas
            String nomeArquivo = "memoria_calculadora.txt";

            // Tenta gravar o valor no arquivo
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(nomeArquivo, true))) {
                // Escreve a conta no arquivo e adiciona uma nova linha
                writer.write(conta);
                writer.newLine();
                JOptionPane.showMessageDialog(null, "Conta salva na memória!");
            } catch (IOException e) {
                // Exibe um erro se houver problemas ao escrever no arquivo
                JOptionPane.showMessageDialog(null, "Erro ao salvar a conta: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "O visor está vazio, nada para salvar.");
        }

    }//GEN-LAST:event_jBtMemoriaActionPerformed


    private void jBtIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtIgualActionPerformed

        // TODO add your handling code here:
        num2 = Double.parseDouble(jtfVisor.getText());

        if (jtfVisor.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Nenhuma operação solicitada!");//Verifica se usa o igual com o visor vazio

        } else {

            switch (op) {

                case '+':

                    num2 = Double.parseDouble(jtfVisor.getText());//Armazena o segundo numero

                    jtfVisor.setText(String.valueOf(num1 + num2));//Faz a operação

                    break;

                case '-':

                    num2 = Double.parseDouble(jtfVisor.getText());

                    jtfVisor.setText(String.valueOf(num1 - num2));

                    break;

                case '*':

                    num2 = Double.parseDouble(jtfVisor.getText());

                    jtfVisor.setText(String.valueOf(num1 * num2));

                    break;

                case '/':

                    if (num2 == 0) { //Verifica ha possibilidade de fazer a divisao

                        JOptionPane.showMessageDialog(null, "Não é possivel fazer uma divisão por zero");

                    } else {

                        num2 = Double.parseDouble(jtfVisor.getText());
                        jtfVisor.setText(String.valueOf(num1 / num2));
                    }
                    break;
                case '%':
                    num2 = Double.parseDouble(jtfVisor.getText());
                    //faz a multiplicação e a divisao, depois a conversao
                    double resultado = (num1 / 100) * 2;
                    jtfVisor.setText(String.valueOf(resultado));
                    break;
                default:
                    throw new AssertionError();
            }
        }
    }//GEN-LAST:event_jBtIgualActionPerformed


    private void jBtPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPontoActionPerformed
        // TODO add your handling code here:
        //faz a verificacao para caso ja exista um ponto
        if (jtfVisor.getText().contains(".")) {
            JOptionPane.showMessageDialog(null, "Virgula já foi adicionada" + " ao valor");
        } else {
            jtfVisor.setText(jtfVisor.getText() + ".");
        }
    }//GEN-LAST:event_jBtPontoActionPerformed

    private void jBtMemRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtMemRecActionPerformed

        // TODO add your handling code here:
// Nome do arquivo onde as contas estão salvas
        String nomeArquivo = "memoria_calculadora.txt";

        // StringBuilder para armazenar todas as contas lidas do arquivo
        StringBuilder contasSalvas = new StringBuilder();

        // Tenta ler as contas do arquivo
        try (BufferedReader reader = new BufferedReader(new FileReader(nomeArquivo))) {
            String linha;

            // Lê cada linha do arquivo
            while ((linha = reader.readLine()) != null) {
                // Adiciona a linha ao StringBuilder
                contasSalvas.append(linha).append("\n");
            }

            // Verifica se há algo no arquivo
            if (contasSalvas.length() > 0) {
                // Exibe todas as contas no visor ou em um JOptionPane
                jtfVisor.setText(contasSalvas.toString());
            } else {
                JOptionPane.showMessageDialog(null, "Nenhuma conta foi salva na memória.");
            }
        } catch (IOException e) {
            // Exibe um erro se houver problemas ao ler o arquivo
            JOptionPane.showMessageDialog(null, "Erro ao ler a memória: " + e.getMessage());
        }
    }//GEN-LAST:event_jBtMemRecActionPerformed

    private void jBtPorcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPorcentagemActionPerformed
        // TODO add your handling code here:

        num1 = Double.parseDouble(jtfVisor.getText());

        op = '%';

        jtfVisor.setText("");
    }//GEN-LAST:event_jBtPorcentagemActionPerformed

    private void jmbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbExitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Fechando a calculadora...");
        System.exit(0);
    }//GEN-LAST:event_jmbExitActionPerformed

    /**
     *
     * @param args the command line arguments
     *
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.

         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 

         */
        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;

                }

            }

        } catch (ClassNotFoundException ex) {

            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {

            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {

            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new TelaPrincipal().setVisible(true);

            }

        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAdicao;
    private javax.swing.JButton jBtApagar;
    private javax.swing.JButton jBtCE;
    private javax.swing.JButton jBtCinco;
    private javax.swing.JButton jBtDivisao;
    private javax.swing.JButton jBtDois;
    private javax.swing.JButton jBtIgual;
    private javax.swing.JButton jBtMemRec;
    private javax.swing.JButton jBtMemoria;
    private javax.swing.JButton jBtMultplicacao;
    private javax.swing.JButton jBtNove;
    private javax.swing.JButton jBtOito;
    private javax.swing.JButton jBtPonto;
    private javax.swing.JButton jBtPorcentagem;
    private javax.swing.JButton jBtQuatro;
    private javax.swing.JButton jBtSeis;
    private javax.swing.JButton jBtSete;
    private javax.swing.JButton jBtSubtracao;
    private javax.swing.JButton jBtTres;
    private javax.swing.JButton jBtUm;
    private javax.swing.JButton jBtZero;
    private javax.swing.JMenu jmbConversor;
    private javax.swing.JMenuItem jmbConversorDeVelocidade;
    private javax.swing.JMenuItem jmbExit;
    private javax.swing.JMenuBar jmbPrincipal;
    private javax.swing.JMenu jmbSair;
    private javax.swing.JTextField jtfVisor;
    // End of variables declaration//GEN-END:variables

}
