SELECT DISTINCT D.NM_DEPARTAMENTO, E.LIDER
	FROM EMPREGADO E, DEPARTAMENTO D
	WHERE E.ID_DEPARTAMENTO = D.ID_DEPARTAMENTO;
    
    SELECT * FROM EMPREGADO
    ORDER BY NM_EMPREGADO
    LIMIT 2,1;
    
    SELECT * , (SALARIO + coalesce(COMISSAO,0))'Total' 
    FROM EMPREGADO;
    
    SELECT *, (2024 - YEAR(DATA_CONTRATACAO))'TEMPO'
		FROM EMPREGADO;
        
    SELECT *,  
		CASE 
			WHEN NM_DEPARTAMENTO LIKE 'CONTABIL' THEN 'ZEZIN GRAUDOS'
            WHEN NM_DEPARTAMENTO LIKE 'PESQUISA E DESENVOLVIMENTO' THEN 'PESQUISADORES DOS DEVS'
            WHEN NM_DEPARTAMENTO LIKE 'VENDAS' THEN 'PERIGO'
            ELSE 'TOM CRUSE'
        END 'APELIDOS'
    FROM DEPARTAMENTO;  
    
    SELECT *, (SALARIO+coalesce(COMISSAO,0))'TOTAL', 
		CASE 
			WHEN (SALARIO+coalesce(COMISSAO,0)) >= 3000 THEN 'GANHA BEM'
            WHEN (SALARIO+coalesce(COMISSAO,0)) >=2250 THEN 'GANHA MAIS OU MENOS'
            ELSE 'QUER ESMOLA'
        END 'STATUS'   
    FROM EMPREGADO; 
    
    SELECT CONCAT(NM_EMPREGADO, ' - ', FUNCAO) 'NOME' FROM EMPREGADO;
    SELECT CONCAT(NM_EMPREGADO, ' - ', LOWER (FUNCAO)) 'NOME' FROM EMPREGADO;
    SELECT CONCAT(NM_EMPREGADO, ' - ', SUBSTRING(FUNCAO,1,1),
		LOWER(SUBSTRING(FUNCAO,2,LENGTH(FUNCAO))) 'NOME' FROM EMPREGADO;
        
    SELECT char_length(NM_EMPREGADO) FROM EMPREGADO;    
    
    SELECT replace(NM_EMPREGADO, 'A','@')  FROM EMPREGADO;  
    SELECT RPAD(NM_EMPREGADO,10,'*'), LEFT(NM_EMPREGADO,1)FROM EMPREGADO;
    SELECT RPAD(LEFT (NM_EMPREGADO,1), CHAR_LENGTH(NM_EMPREGADO),'*')
		FROM EMPREGADO;
        
    SELECT NOW();
    SELECT DATE_FORMAT(CURDATE(), '%D/%M/%Y');
    
    SELECT MONTH(CURDATE());